name: Setup OCR Model
description: Downloads and caches the CRNN OCR model for Arcaea Offline

runs:
  using: composite
  steps:
    - name: Cache CRNN OCR model
      id: cache-ocr
      uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
      with:
        path: app/src/main/assets/ocr
        key: ocr-models_crnn-1.0.2

    - name: Ensure CRNN OCR model asset folder exists
      if: steps.cache-ocr.outputs.cache-hit != 'true'
      run: mkdir -p app/src/main/assets/ocr
      shell: bash

    - name: Download CRNN OCR model to assets
      if: steps.cache-ocr.outputs.cache-hit != 'true'
      run: |
        curl -L -o app/src/main/assets/ocr/model_patched.onnx https://huggingface.co/ArcaeaOffline/crnn-pytorch/resolve/main/model-early_stop_patched.onnx
        curl -L -o app/src/main/assets/ocr/model_info.json https://huggingface.co/ArcaeaOffline/crnn-pytorch/resolve/main/model_info.json
      shell: bash
