name: Setup Toolchain
description: Sets up Java and Gradle for building

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        java-version: 17
        distribution: temurin
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      with:
        cache-provider: basic
