name: Build unstableRelease APK

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Xmx6g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8

    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Setup Toolchain
        uses: ./.github/actions/setup-toolchain

      - name: Release keystore file
        run: base64 -d <<< "${{ secrets.KEYSTORE_FILE_BASE64 }}" > arcaea_offline.jks

      - name: Release local.properties file
        run: base64 -d <<< "${{ secrets.LOCAL_PROPERTIES_FILE_BASE64 }}" > local.properties

      - name: Setup OCR Model
        uses: ./.github/actions/setup-ocr-model

      - name: Build APK using gradle
        run: ./gradlew assembleUnstableRelease

      - name: Verify APK signing
        run: |
          # Locate the latest build tools
          BUILD_TOOLS_VERSION=$(ls $ANDROID_HOME/build-tools/ | sort -V | tail -n 1)
          # Adding build tools to PATH for this step only
          PATH=$ANDROID_HOME/build-tools/$BUILD_TOOLS_VERSION:$PATH
          
          apksigner verify --verbose --min-sdk-version 24 app/build/outputs/apk/unstable/release/app-unstable-arm64-v8a-release.apk
          apksigner verify --verbose --min-sdk-version 24 app/build/outputs/apk/unstable/release/app-unstable-armeabi-v7a-release.apk
          apksigner verify --verbose --min-sdk-version 24 app/build/outputs/apk/unstable/release/app-unstable-x86_64-release.apk
          apksigner verify --verbose --min-sdk-version 24 app/build/outputs/apk/unstable/release/app-unstable-x86-release.apk
          apksigner verify --verbose --min-sdk-version 24 app/build/outputs/apk/unstable/release/app-unstable-universal-release.apk

      - name: Upload build result artifact (arm64-v8a)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: arm64-v8a
          path: app/build/outputs/apk/unstable/release/app-unstable-arm64-v8a-release.apk
          archive: false

      - name: Upload build result artifact (armeabi-v7a)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: armeabi-v7a
          path: app/build/outputs/apk/unstable/release/app-unstable-armeabi-v7a-release.apk
          archive: false

      - name: Upload build result artifact (x86_64)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: x86_64
          path: app/build/outputs/apk/unstable/release/app-unstable-x86_64-release.apk
          archive: false

      - name: Upload build result artifact (x86)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: x86
          path: app/build/outputs/apk/unstable/release/app-unstable-x86-release.apk
          archive: false

      - name: Upload build result artifact (universal)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: universal
          path: app/build/outputs/apk/unstable/release/app-unstable-universal-release.apk
          archive: false

      - name: Zip mappings for release
        run: zip app/build/outputs/mappings.zip -j app/build/outputs/mapping/unstableRelease/*

      - name: Upload mappings to artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: proguard-mappings
          path: app/build/outputs/mappings.zip
          archive: false

      - name: Draft a release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          discussion_category_name: New releases
          draft: true
          generate_release_notes: true
          files: |
            app/build/outputs/apk/unstable/release/app-unstable-*-release.apk
            app/build/outputs/mappings.zip
