name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  general:
    name: General Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'gradle'

      - name: Grant Execute Permission to Gradlew
        run: chmod +x ./gradlew

      - name: Release local.properties file
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: 'local.properties'
          fileDir: ${{ github.workspace }}
          encodedString: ${{ secrets.LOCAL_PROPERTIES_FILE_BASE64 }}

      - name: Run ktlint
        run: ./gradlew lintKotlin --no-daemon
