name: Code Quality Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  general-checks:
    name: Run General Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'gradle'

      - name: Grant Execute Permission to Gradlew
        run: chmod +x ./gradlew

      - name: Run ktlint
        run: ./gradlew lintKotlin --no-daemon
