name: connectedAndroidTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096M -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.caching=true"

jobs:
  test:
    name: Run Connected Android Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - api-level: 24
            target: default
          - api-level: 36
            target: google_apis

    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Setup Toolchain
        uses: ./.github/actions/setup-toolchain

      - name: Release local.properties file
        run: cp local.defaults.properties local.properties

      - name: Setup OCR Model
        uses: ./.github/actions/setup-ocr-model

      # Avoid building the application when AVD is running, so Gradle can use more RAM
      - name: Build Application
        run: ./gradlew assembleDebugAndroidTest --stacktrace

      # android-emulator-runner configurations start here
      # See also https://github.com/ReactiveCircus/android-emulator-runner#usage--examples
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run UI Tests
        id: ui_tests
        uses: reactivecircus/android-emulator-runner@e89f39f1abbbd05b1113a29cf4db69e7540cae5a # v2.37.0
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          emulator-options: -no-metrics -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          disable-animations: true
          script: .github/scripts/connected-android-test.sh

      - name: Upload Test Results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ !cancelled() }}  # run this step even if previous step failed
        with:
          name: test-results-api${{ matrix.api-level }}-${{ matrix.target }}
          path: ${{ steps.ui_tests.outputs.reports-path }}
